# -*- coding: utf-8 -*-
"""PandasBD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wUDcGD33wWnmdqm7iFtcJrTe09SsoFK
"""

#exemplo utilização
import pandas as pd

#Criando um DataFrame
data = {
    'Nome': ['Ana', 'João', 'Maria'],
    'Idade': [25, 30, 28],
    'Salario': [5000, 7000, 6000]
}
df = pd.DataFrame(data)

print(df.head())

print(df.info())

print(df.describe())

import numpy as np

#Criando um array
arr = np.array([1, 2, 3, 4, 5])

#operações vetorizadas
print(arr + 10) # soma 10 a cada elemento
print(arr - 1) # subtrai 1 de cada elemento
print(arr * 2) # multiplica cada elemento por 2
print(arr ** 2) # eleva cada elemento por 2
print(arr / 2) # divide cada elemento por 2

# 1 - criação de dados fictícios com NumPy
np.random.seed(42)
meses = np.array(['Jan', 'Fev', 'Mar', 'Abr', 'Mai'])
vendas = np.random.randint(100, 500, size=5)
custos = vendas * np.random.uniform(0.3, 0.7, size=5)
#escolher numero aleatorio randômico

print(meses)
print(vendas)
print(custos)

# 2 - Conversão para DataFrame do Pandas
dados = pd.DataFrame({
    'Mes': meses,
    'Vendas (R$)': vendas,
    'Custos (R$)': np.round(custos,2),
    'Clientes': np.random.poisson(lam=50,size=5) #escolher numero aleatorio randômico
})
print(dados)

dados['Lucro (R$)'] = dados['Vendas (R$)'] - dados['Custos (R$)'] # adição de colouna
print(dados)

dados['Teste (R$)'] = dados['Vendas (R$)'] * dados['Lucro (R$)'] # adição de colouna
print(dados)

dados['Margem %'] = np.round((dados['Lucro (R$)']/ dados['Vendas (R$)']) * 100, 1) #Arredondamento para 1 casa decimal
print(dados)